version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip" # Can also be "uv" since you have a uv.lock
    directory: "/agent/python_agent"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0