# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Runs the semantic-release action for all new pushes to the main branch.
##   This will create new release tags, create GitHub releases, publish the
##   NPM package, and update the CHANGELOG.md.

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          fetch-depth: 0

      - name: Setup Node for Dependency Installation
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

        with:
          node-version: 22
          cache: npm
          cache-dependency-path: client/web/package-lock.json

      - name: Install dependencies
        working-directory: client/web
        run: npm ci

      - name: Setup Node for Publishing
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

        with:
          node-version: 20
          registry-url: "https://wombat-dressing-room.appspot.com/"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          NPM_TOKEN: ${{ secrets.NPM_WOMBAT_TOKEN }}
          NODE_PATH: ${{ github.workspace }}/client/web/node_modules
        run: npx semantic-release
