# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Runs the release-please action for all new pushes to the main branch.
##   This will create new release-PRs, create GitHub releases and update
##   the CHANGELOG.md.

# Disabled automatic pushes to prevent conflict with semantic-release.
# Can still be triggered manually via Actions UI if needed.
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0


        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      # Everything below is for NPM publishing when a release is cut.
      # Note the "if" statement on all commands to make sure that publishing
      # only happens when a release is cut.

      - if: ${{ steps.release.outputs.release_created }}
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


      - if: ${{ steps.release.outputs.release_created }}
        name: Setup Node for Dependency Installation
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

        with:
          node-version: 22

      - if: ${{ steps.release.outputs.release_created }}
        name: Install Dependencies
        working-directory: client/web
        run: npm ci

      # Now configure node with the registry used for publishing
      - if: ${{ steps.release.outputs.release_created }}
        name: Setup Node for Publishing
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

        with:
          node-version: 20
          registry-url: "https://wombat-dressing-room.appspot.com/"

      - if: ${{ steps.release.outputs.release_created }}
        name: Publish
        # npm publish will trigger the build via the prepack hook
        working-directory: client/web
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WOMBAT_TOKEN }}
